services:
  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest # Self-Hosted build (recommended)
    # image: bentopdfteam/bentopdf-simple:latest     # Self-Hosted build (Docker Hub)
    # image: ghcr.io/alam00000/bentopdf:latest       # Commercial build (bentopdf.com / commercial license holders)
    container_name: imgproxy
    ports:
      - '3000:8080'
    restart: unless-stopped